-- AlterTable
ALTER TABLE `UserChatLog` MODIFY `actionType` ENUM('ASKBOOKINGWELCOME', 'NEWBOOKINGMSG', 'ANSNEWBOOKINGMSG', 'ASKBOOKINGAVAILABLE', 'ANSBOOKINGAVAILABLE', 'CONFIRMBOOKING', 'ANSCONFIRMBOOKING', 'PRIVACYAGREE', 'FINALBOOKINGCHECK', 'TEXT') NOT NULL;
