version: '3.6'

services:
  mysql:
    image: mysql
    platform: linux/amd64
    restart: always
    ports:
      - 3323:3306
    environment:
      MYSQL_ROOT_HOST: localhost
      MYSQL_ROOT_PASSWORD: root1
      MYSQL_DATABASE: travelit-api
      MYSQL_USER: idealbloom
      MYSQL_PASSWORD: idealbloom1

    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql

volumes:
  db:
