-- AlterTable
ALTER TABLE `BookingChatLog` MODIFY `bookingActionType` ENUM('ASKBOOKINGWELCOME', 'NEWBOOKINGMSG', 'ANSNEWBOOKINGMSG', 'ASKBOOKINGAVAILABLE', 'ANSBOOKINGAVAILABLE', 'ANSBOOKINGAVAILABLEREJECT', 'ASKBOOKINGCANCEL', 'ASKBOOKINGCANCELCHK', 'CONFIRMBOOKING', 'ANSCONFIRMBOOKING', 'PRIVACYAGREE', 'FINALBOOKINGCHECK', 'USERCANCELAFTERBOOKING', 'USERCANCELAFTERBOOKINGCHK', 'TEXT') NOT NULL;

-- AlterTable
ALTER TABLE `BookingInfo` MODIFY `status` ENUM('RESERVED', 'CUSTOMERPRECANCEL', 'COMPANYPRECANCEL', 'CUSTOMERCANCEL', 'COMPANYCANCEL', 'NOSHOW', 'VISITED') NOT NULL DEFAULT 'RESERVED';
