-- AlterTable
ALTER TABLE `UserChatActionInputParam` ADD COLUMN `customerCancel` BOOLEAN NULL;

-- AlterTable
ALTER TABLE `UserChatLog` MODIFY `actionType` ENUM('ASKBOOKINGWELCOME', 'NEWBOOKINGMSG', 'ANSNEWBOOKINGMSG', 'ASKBOOKINGAVAILABLE', 'ANSBOOKINGAVAILABLE', 'ASKBOOKINGCANCEL', 'ASKBOOKINGCANCELCHK', 'CONFIRMBOOKING', 'ANSCONFIRMBOOKING', 'PRIVACYAGREE', 'FINALBOOKINGCHECK', 'TEXT') NOT NULL;
