-- AlterTable
ALTER TABLE `BookingChatLog` MODIFY `bookingActionType` ENUM('ASKBOOKINGWELCOME', 'NEWBOOKINGMSG', 'ANSNEWBOOKINGMSG', 'ASKBOOKINGAVAILABLE', 'ANSBOOKINGAVAILABLE', 'ASKBOOKINGCANCEL', 'ASKBOOKINGCANCELCHK', 'CONFIRMBOOKING', 'ANSCONFIRMBOOKING', 'PRIVACYAGREE', 'FINALBOOKINGCHECK', 'USERCANCELAFTERBOOKING', 'USERCANCELAFTERBOOKINGCHK', 'TEXT') NOT NULL;
