-- AlterTable
ALTER TABLE `MockBookingDotComHotelResource` ADD COLUMN `reqType` ENUM('SEARCH_HOTELS_BY_COORDINATES', 'SEARCH_LOCATIONS', 'FILTERS_FOR_SEARCH', 'SEARCH_HOTELS') NOT NULL DEFAULT 'SEARCH_HOTELS_BY_COORDINATES';
