-- CreateTable
CREATE TABLE `SearchHotelRes` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `min_total_price` DOUBLE NOT NULL,
    `gross_amount` DOUBLE NOT NULL,
    `included_taxes_and_charges_amount` DOUBLE NOT NULL,
    `net_amount` DOUBLE NOT NULL,
    `countrycode` VARCHAR(191) NOT NULL,
    `default_language` VARCHAR(191) NOT NULL,
    `address` VARCHAR(191) NOT NULL,
    `city` VARCHAR(191) NOT NULL,
    `city_name_en` VARCHAR(191) NOT NULL,
    `checkin` VARCHAR(191) NOT NULL,
    `checkout` VARCHAR(191) NOT NULL,
    `distance` DOUBLE NOT NULL,
    `review_score_word` VARCHAR(191) NOT NULL,
    `review_score` DOUBLE NOT NULL,
    `currency_code` VARCHAR(191) NOT NULL,
    `timezone` VARCHAR(191) NOT NULL,
    `urgency_message` VARCHAR(191) NOT NULL,
    `hotel_id` INTEGER NOT NULL,
    `hotel_name` VARCHAR(191) NOT NULL,
    `latitude` DOUBLE NOT NULL,
    `longitude` DOUBLE NOT NULL,
    `url` VARCHAR(191) NOT NULL,
    `accommodation_type_name` VARCHAR(191) NOT NULL,
    `zip` VARCHAR(191) NOT NULL,
    `main_photo_url` VARCHAR(191) NOT NULL,
    `max_photo_url` VARCHAR(191) NOT NULL,
    `hotel_facilities` VARCHAR(191) NOT NULL,
    `has_swimming_pool` INTEGER NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
