-- CreateTable
CREATE TABLE `IBEventPromotion` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `status` ENUM('OPENED', 'EXPIRED', 'STOPPED', 'PREPARING', 'TERMINATED') NOT NULL DEFAULT 'OPENED',
    `name` TEXT NOT NULL,
    `desc` LONGTEXT NOT NULL,
    `price` INTEGER NOT NULL DEFAULT 0,
    `currency` ENUM('USD', 'KRW', 'JPY', 'CNY', 'EUR') NOT NULL DEFAULT 'KRW',
    `payType` ENUM('PERIODIC_DAY', 'PERIODIC_WEEK', 'PERIODIC_MONTH', 'PERIODIC_YEAR', 'ONCE', 'FREE') NOT NULL DEFAULT 'ONCE',
    `startDate` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `endDate` DATETIME(3) NULL,
    `byWhom` VARCHAR(191) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `IBEventApplication` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `content` TEXT NOT NULL,
    `promotionId` INTEGER NULL,
    `userId` INTEGER NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `IBEventApplication` ADD CONSTRAINT `IBEventApplication_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `IBEventApplication` ADD CONSTRAINT `IBEventApplication_promotionId_fkey` FOREIGN KEY (`promotionId`) REFERENCES `IBEventPromotion`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
